### ISSUE TITLE
canonicalize trimming leading color code from all lines after first

### ISSUE THREAD

**Issue by thatfunkymunki** [lalbornoz/roar#1]
see attached files- first color code is missing from lines 2+
[asdf_original.txt](https://github.com/lalbornoz/MiRCARTools/files/2108565/asdf_original.txt)
[asdf_output.txt](https://github.com/lalbornoz/MiRCARTools/files/2108566/asdf_output.txt)
[asdf_expected.txt](https://github.com/lalbornoz/MiRCARTools/files/2108567/asdf_expected.txt)
[view in irssi](https://i.imgur.com/drqRGUW.png)

**Comment by lalbornoz** [comment]
Fixed in 5f99672, cheers!
